apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lakehouse-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/OmalCooray/test-k8s-configs
      targetRevision: master
      path: charts/lakehouse-ui
      helm:
        valueFiles:
          - $values/environments/local/values/lakehouse-ui.yaml
    - repoURL: https://github.com/OmalCooray/test-k8s-configs
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: lakehouse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
