apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: polaris-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/OmalCooray/test-k8s-configs
      targetRevision: master
      path: charts/polaris-postgres
      helm:
        valueFiles:
          - $values/environments/local/values/polaris-postgres.yaml
    - repoURL: https://github.com/OmalCooray/test-k8s-configs
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: lakehouse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
