apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-local
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/OmalCooray/test-k8s-configs
    targetRevision: master
    path: environments/local/apps
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
