{
 "title": "Airflow 3",
 "description": "Dashboard monitoring Airflow 3.1.6",
 "time": { "from": "2026-02-07T10:19:12.346Z", "to": "2026-02-07T13:53:04.754Z" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "System Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database Lock",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_scheduler_critical_section_duration",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduler Heartbeat",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(airflow_scheduler_scheduler_loop_duration[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(airflow_serde_load_serializers[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Query Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "airflow_scheduler_critical_section_query_duration",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Triggerer Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Global Capacity Remaining",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_triggerer_capacity_left",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Triggerer Heartbeat",
   "type": "stat",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(airflow_triggerer_heartbeat_total[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capacity per Triggerer Instance",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{__name__=~\"airflow_triggerer_capacity_left_.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Executor & Worker Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Cluster Spare Capacity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_executor_open_slots", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Task Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "airflow_executor_running_tasks ",
     "legendFormat": "__auto"
    },
    { "expr": "airflow_executor_queued_tasks ", "legendFormat": "__auto" }
   ]
  },
  { "title": "Pool Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Queued Tasks by Pool",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{__name__=~\"airflow_pool_queued_slots_.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduled Slots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{__name__=~\"airflow_pool_scheduled_slots_.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pool capacity Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "{__name__=~\"airflow_pool_open_slots_.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Tasks by Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "{__name__=~\"airflow_pool_running_slots_.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deferred Slots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "{__name__=~\"airflow_pool_deferred_slots_.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DAG Processing Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "DAG Parse Lag",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "{__name__=~\"airflow_dag_processing_last_run_seconds_ago_.*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}